version: '3'

services:
  vuejs:
    image: node:alpine
    user: "node"
    volumes:
      - "./front:/var/www"
      - "./.env:/var/www/.env"
    ports:
      - "8080:8080"
    links:
      - api
    environment:
      - URL_MONGO=mongodb://${DB_USER}:${DB_PASSWORD}@mongo
    command: /bin/sh -c "cd /var/www && npm run serve"


  api:
    image: node:alpine
    user: "node"
    volumes:
      - "./api:/var/www"
      - "./.env:/var/www/.env"
    ports:
      - "8082:3000"
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://${DB_USER}:${DB_PASSWORD}@mongo
    command: /bin/sh -c "cd /var/www && ./node_modules/.bin/pm2 start startup.json --name API --no-daemon"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
    depends_on:
      - mongo
    
  mongo:
    image: mongo:latest
    volumes:
      - "./database/mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
